baseURL = "https://cedscherer.netlify.io"
title = "Cedric Scherer"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.info]
description = ""
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon_pers.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Cédric Scherer"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "cedricphilippscherer@gmail.com"
github = "Z3tt"
twitter = "CedScherer"

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
